apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv
spec:
  capacity:
    storage: 100Mi  # Doit correspondre à la demande du PVC
  accessModes:
    - ReadWriteMany  # Doit correspondre à la demande du PVC
  hostPath:
    path: /mnt/data/wordpress  # Chemin sur le nœud pour Minikube
