apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    app: blog
  ports:
    - protocol: TCP
      port: 80        
      targetPort: 80  
  type: ClusterIP  
