apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: middle  
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: blog  
  template:
    metadata:
      labels:
        app: blog  
    spec:
      containers:
      - name: wordpress
        image: wordpress:latest 
        env:
          - name: WORDPRESS_DB_USER
            valueFrom:
              configMapKeyRef:
                name: mysql-configmap  
                key: MYSQL_USER
          - name: WORDPRESS_DB_NAME
            valueFrom:
              configMapKeyRef:
                name: mysql-configmap  
                key: MYSQL_DATABASE
          - name: WORDPRESS_DB_HOST
            value: "mysql.database.svc.cluster.local" 
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret  
                key: MYSQL_PASSWORD
        volumeMounts: 
        - mountPath: /var/www/html  
          name: wordpress-storage  
      volumes:
      - name: wordpress-storage
        persistentVolumeClaim:
          claimName: wordpress-pvc 
